//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InscripcionCol.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RegistroColegioDBEntities : DbContext
    {
        public RegistroColegioDBEntities()
            : base("name=RegistroColegioDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBeca> TBeca { get; set; }
        public virtual DbSet<TComprobante> TComprobante { get; set; }
        public virtual DbSet<TContacto> TContacto { get; set; }
        public virtual DbSet<TCurso> TCurso { get; set; }
        public virtual DbSet<TDir_Est> TDir_Est { get; set; }
        public virtual DbSet<TDireccion> TDireccion { get; set; }
        public virtual DbSet<TDocente> TDocente { get; set; }
        public virtual DbSet<TEstudiante> TEstudiante { get; set; }
        public virtual DbSet<TNacimiento> TNacimiento { get; set; }
        public virtual DbSet<TRegistro> TRegistro { get; set; }
        public virtual DbSet<TTutor> TTutor { get; set; }
        public virtual DbSet<TTutor_Est> TTutor_Est { get; set; }
        public virtual DbSet<TUsuario> TUsuario { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
