//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InscripcionCol.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RegistroColegioDBEntities : DbContext
    {
        public RegistroColegioDBEntities()
            : base("name=RegistroColegioDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TBeca> TBeca { get; set; }
        public DbSet<TComprobante> TComprobante { get; set; }
        public DbSet<TContacto> TContacto { get; set; }
        public DbSet<TCurso> TCurso { get; set; }
        public DbSet<TDireccion> TDireccion { get; set; }
        public DbSet<TDocente> TDocente { get; set; }
        public DbSet<TEstudiante> TEstudiante { get; set; }
        public DbSet<TNacimiento> TNacimiento { get; set; }
        public DbSet<TRegistro> TRegistro { get; set; }
        public DbSet<TTutor> TTutor { get; set; }
        public DbSet<TUsuario> TUsuario { get; set; }
    }
}
