//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InscripcionCol.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBeca
    {
        public TBeca()
        {
            this.TEstudiante = new HashSet<TEstudiante>();
        }
    
        public int id_beca { get; set; }
        public string tipo { get; set; }
        public decimal monto { get; set; }
        public int id_estudiante { get; set; }
    
        public virtual ICollection<TEstudiante> TEstudiante { get; set; }
    }
}
