//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InscripcionCol.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TComprobante
    {
        public int id_comp { get; set; }
        public string lugar_dpto { get; set; }
        public System.DateTime fecha_reg { get; set; }
        public int id_estudiante { get; set; }
        public int id_curso { get; set; }
        public int id_tutor { get; set; }
    
        public virtual TCurso TCurso { get; set; }
        public virtual TEstudiante TEstudiante { get; set; }
        public virtual TTutor TTutor { get; set; }
    }
}
