//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InscripcionCol.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCurso
    {
        public TCurso()
        {
            this.TComprobante = new HashSet<TComprobante>();
            this.TDocente = new HashSet<TDocente>();
        }
    
        public int id_curso { get; set; }
        public int grado { get; set; }
        public string paralelo { get; set; }
        public int cupo_total { get; set; }
    
        public virtual ICollection<TComprobante> TComprobante { get; set; }
        public virtual ICollection<TDocente> TDocente { get; set; }
    }
}
