//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InscripcionCol.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDireccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TDireccion()
        {
            this.TContacto = new HashSet<TContacto>();
            this.TDir_Est = new HashSet<TDir_Est>();
        }
    
        public int id_direccion { get; set; }
        public string dpto { get; set; }
        public string provincia { get; set; }
        public string municipio { get; set; }
        public string localidad { get; set; }
        public string zona { get; set; }
        public string avenida { get; set; }
        public string nro_vivienda { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TContacto> TContacto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDir_Est> TDir_Est { get; set; }
    }
}
