//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InscripcionCol.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDocente
    {
        public int id_docente { get; set; }
        public string especialidad { get; set; }
        public string nivel_educativo { get; set; }
        public string grado_acad { get; set; }
        public System.DateTime fec_contratacion { get; set; }
        public int id_registro { get; set; }
        public int id_curso { get; set; }
    
        public virtual TCurso TCurso { get; set; }
        public virtual TRegistro TRegistro { get; set; }
    }
}
