//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InscripcionCol.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEstudiante
    {
        public TEstudiante()
        {
            this.TComprobante = new HashSet<TComprobante>();
            this.TNacimiento = new HashSet<TNacimiento>();
            this.TBeca = new HashSet<TBeca>();
            this.TDireccion = new HashSet<TDireccion>();
            this.TTutor = new HashSet<TTutor>();
        }
    
        public int id_estudiante { get; set; }
        public string ap_paterno { get; set; }
        public string ap_materno { get; set; }
        public string nombre { get; set; }
        public int ci { get; set; }
        public string complemento { get; set; }
        public string expedido { get; set; }
        public string codigo_rude { get; set; }
        public string sexo { get; set; }
        public System.DateTime fec_nacimiento { get; set; }
        public int grado_sec { get; set; }
    
        public virtual ICollection<TComprobante> TComprobante { get; set; }
        public virtual ICollection<TNacimiento> TNacimiento { get; set; }
        public virtual ICollection<TBeca> TBeca { get; set; }
        public virtual ICollection<TDireccion> TDireccion { get; set; }
        public virtual ICollection<TTutor> TTutor { get; set; }
    }
}
