//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InscripcionCol.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRegistro
    {
        public TRegistro()
        {
            this.TDocente = new HashSet<TDocente>();
            this.TUsuario = new HashSet<TUsuario>();
        }
    
        public int id_registro { get; set; }
        public int ci { get; set; }
        public string nombre { get; set; }
        public string ap_paterno { get; set; }
        public string ap_materno { get; set; }
        public string direccion { get; set; }
        public int celular { get; set; }
        public string sexo { get; set; }
        public System.DateTime fecha_nac { get; set; }
    
        public virtual ICollection<TDocente> TDocente { get; set; }
        public virtual ICollection<TUsuario> TUsuario { get; set; }
    }
}
