//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InscripcionCol.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTutor
    {
        public TTutor()
        {
            this.TComprobante = new HashSet<TComprobante>();
            this.TEstudiante = new HashSet<TEstudiante>();
        }
    
        public int id_tutor { get; set; }
        public int ci { get; set; }
        public string complemento { get; set; }
        public string expedido { get; set; }
        public string ap_paterno { get; set; }
        public string ap_materno { get; set; }
        public string nombre { get; set; }
        public int id_estudiante { get; set; }
    
        public virtual ICollection<TComprobante> TComprobante { get; set; }
        public virtual ICollection<TEstudiante> TEstudiante { get; set; }
    }
}
